version: '3.3'
volumes:
  postgres-data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - /var/log/postgresql/:/var/log/postgresql/
    env_file:
      - infomodel/infomodel/.env
    ports:
      - "5432:5432"